# Setup
title:            cgel
tagline:          A blog about AI
description:      'A blog about AI'
baseurl:          /

paginate:            1

markdown:    kramdown

# About/contact
author:
  name:              Carles Gelada
  email:             carlesgelada@hotmail.com

twitter_username: carlesgelada
github_username: cgel

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

highlighter:      pygments
